version: '3.8'

services:
  db:
    image: postgres:17.3 #latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres       # Database name
      POSTGRES_USER: root         # Database user
      POSTGRES_PASSWORD: root     # Database password
    ports:
      - "5432:5432"                    # Expose PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data

volumes:
  postgres_data: